### ISSUE TITLE
Plural block integrity error

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#157]
Blocking the canonical table.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: could not create unique index "pl_bk_id_idx_eba2b0eb-a5ff-41e1-8d6c-cf2344ca2edb_cr"
DETAIL:  Key (block_id, record_id)=(5894, 65744818-b93f-4412-8a14-cd6ad82a6654) is duplicated.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fgregg/public/dedupe-api/api/queue.py", line 80, in processMessage
    upd_args['return_value'] = func(*args, **kwargs)
  File "/home/fgregg/public/dedupe-api/api/utils/delayed_tasks.py", line 92, in bulkMarkClusters
    '''), entity_count=count, id=session_id)
  File "/home/fgregg/public/dedupe-api/api/utils/delayed_tasks.py", line 643, in dedupeCanon
    del block_gen
  File "/home/fgregg/public/dedupe-api/api/utils/db_functions.py", line 583, in writeBlockingMap
    with engine.begin() as c:
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 721, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 870, in _execute_text
    statement, parameters
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (IntegrityError) could not create unique index "pl_bk_id_idx_eba2b0eb-a5ff-41e1-8d6c-cf2344ca2edb_cr"
DETAIL:  Key (block_id, record_id)=(5894, 65744818-b93f-4412-8a14-cd6ad82a6654) is duplicated.
 ' \n            CREATE UNIQUE INDEX "pl_bk_id_idx_eba2b0eb-a5ff-41e1-8d6c-cf2344ca2edb_cr" on "plural_block_eba2b0eb-a5ff-41e1-8d6c-cf2344ca2edb_cr" \n            (block_id, record_id) ' {}
```

**Comment by fgregg** [comment]
After I saw this in the console, on the main session view. It showed that I was at the merge step. When I clicked "merge entities" it said I was done. This may be the error that you had been seeing @evz.

**Comment by evz** [comment]
Do you remember the dataset that produced this?

**Comment by fgregg** [comment]
Federal lobbyists

**Comment by evz** [comment]
For now we are going to hang on to the CSV file that is generated in advance of creating the block table to see if in writing that file we are getting duplicate rows.

**Comment by fgregg** [comment]
Where are we on this?

**Comment by evz** [comment]
This one and #170 and #167 are all impossible to reproduce. Despite having seen them a few times in the wild, I've never been able to figure out what causes them to happen.

**Comment by fgregg** [comment]
After @evz fixed #188, we got some `(DatabaseError) SSL SYSCALL error: EOF detected` errors. Trudging through the posgres and dmesg logs. We found that the postgres server was killed due to an out of memory error.

**Comment by fgregg** [comment]
@evz made fixes suggested here: http://www.postgresql.org/docs/current/static/kernel-resources.html#LINUX-MEMORY-OVERCOMMIT 

These have not been incorporated into our deploy scripts yet.

**Comment by fgregg** [comment]
Described by #195
