### ISSUE TITLE
csv upload error when decoding 

### ISSUE THREAD

**Issue by derekeder** [datamade/dedupe-api#179]
perhaps a python3 issue?

```bash
Traceback (most recent call last):
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/derekeder/.virtualenvs/dedupeapi3/lib/python3.4/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/derekeder/projects/datamade/dedupe-api/api/trainer.py", line 59, in upload
    u = StringIO(convert.convert(u, file_format).decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

```

**Comment by derekeder** [comment]
FYI removing `.decode('utf-8')` from line 59 fixed this, though I wasn't confident enough to commit it.
