### ISSUE TITLE
Getting the following error in stderrr logs, not in sentry

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#212]
From the past 24 hours:

```
Listening for messages...
Traceback (most recent call last):
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(raw_f494c64d-00bc-47c7-9507-236292851ff9_record_id_seq, 2200) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/datamade/dedupe-api/api/queue.py", line 80, in processMessage
    upd_args['return_value'] = func(*args, **kwargs)
  File "/home/datamade/dedupe-api/api/utils/delayed_tasks.py", line 510, in initializeSession
    writeRawTable(**kwargs)
  File "/home/datamade/dedupe-api/api/utils/db_functions.py", line 274, in writeRawTable
    sql_table.create(engine)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/sql/schema.py", line 707, in create
    checkfirst=checkfirst)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1616, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1245, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 120, in traverse_single
    return meth(obj, **kw)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 732, in visit_table
    self.connection.execute(CreateTable(table))
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
    compiled
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/home/datamade/.virtualenvs/dedupe-api/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(raw_f494c64d-00bc-47c7-9507-236292851ff9_record_id_seq, 2200) already exists.
 '\nCREATE TABLE "raw_f494c64d-00bc-47c7-9507-236292851ff9" (\n\tid VARCHAR, \n\timport_reference_id VARCHAR, \n\tcycle VARCHAR, \n\ttransaction_namespace VARCHAR, \n\ttransaction_id VARCHAR, \n\ttransaction_type VARCHAR, \n\tfiling_id VARCHAR, \n\tis_amendment VARCHAR, \n\tamount VARCHAR, \n\tdate VARCHAR, \n\tcontributor_name VARCHAR, \n\tcontributor_ext_id VARCHAR, \n\tcontributor_type VARCHAR, \n\tcontributor_occupation VARCHAR, \n\tcontributor_employer VARCHAR, \n\tcontributor_gender VARCHAR, \n\tcontributor_address VARCHAR, \n\tcontributor_city VARCHAR, \n\tcontributor_state VARCHAR, \n\tcontributor_zipcode VARCHAR, \n\tcontributor_category VARCHAR, \n\torganization_name VARCHAR, \n\torganization_ext_id VARCHAR, \n\tparent_organization_name VARCHAR, \n\tparent_organization_ext_id VARCHAR, \n\trecipient_name VARCHAR, \n\trecipient_ext_id VARCHAR, \n\trecipient_party VARCHAR, \n\trecipient_type VARCHAR, \n\trecipient_state VARCHAR, \n\trecipient_state_held VARCHAR, \n\trecipient_category VARCHAR, \n\tcommittee_name VARCHAR, \n\tcommittee_ext_id VARCHAR, \n\tcommittee_party VARCHAR, \n\tcandidacy_status VARCHAR, \n\tdistrict VARCHAR, \n\tdistrict_held VARCHAR, \n\tseat VARCHAR, \n\tseat_held VARCHAR, \n\tseat_status VARCHAR, \n\tseat_result VARCHAR, \n\trecord_id BIGSERIAL NOT NULL, \n\tPRIMARY KEY (record_id)\n)\n\n' {}
```

**Comment by fgregg** [comment]
Looks like we are still writing and reading from files. I thought we avoided this in a previous round,

**Comment by fgregg** [comment]
Nevermind, it was being logged by sentry, but not pushed to slack. This is very confusing. Can we please push all messages to slack.
