### ISSUE TITLE
Getting strange error when running test_review

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#224]
```bash
nosetests3 -s tests.test_matching:MatchingTest.test_matches_add_entity_getunmatched
Raven is not configured (logging is disabled). Please see the documentation for more information.
session initialized
got sample
<Response streamed [500 INTERNAL SERVER ERROR]>
E
======================================================================
ERROR: test_matches_add_entity_getunmatched (tests.test_matching.MatchingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fgregg/public/dedupe-api/tests/test_matching.py", line 204, in test_matches_add_entity_getunmatched
    obj = json.loads(unmatched.data.decode('utf-8'))['object']
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
nose.proxy.ValueError: Expecting value: line 1 column 1 (char 0)
-------------------- >> begin captured logging << --------------------
root: INFO: Generating grammar tables from /usr/lib/python3.4/lib2to3/Grammar.txt
root: INFO: Generating grammar tables from /usr/lib/python3.4/lib2to3/PatternGrammar.txt
raven.base.Client: INFO: Raven is not configured (logging is disabled). Please see the documentation for more information.
api: INFO: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fgregg/public/dedupe-api/api/auth.py", line 90, in decorated
    api_key = json.loads(request.data).get('api_key')
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 69.852s

FAILED (errors=1)
```

**Comment by fgregg** [comment]
Working fine on the server.

**Comment by evz** [comment]
That seems like a bug. The json library, as it states, expects a ``str`` and, as far as I know, the raw ``request.data`` thing that you get with any Flask request is ``bytes``. Did you try sticking a ``.decode('utf-8')`` on the end of it?
